# Generated by Django 5.1.7 on 2025-05-23 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ganado_Vacuno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_arete', models.CharField(max_length=25, verbose_name='Código de Arete')),
                ('raza', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('sexo', models.CharField(max_length=25)),
                ('lugar_origen', models.CharField(max_length=100, verbose_name='Lugar de origen')),
                ('precio_por_kilo', models.FloatField()),
                ('estaVivo', models.BooleanField(verbose_name='¿Está vivo(a)?')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento (Año-Mes-Día)')),
                ('fecha_compra', models.DateField(verbose_name='Fecha de compra (Año-Mes-Día)')),
                ('agregado', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_datos', models.DateTimeField(auto_now=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dueño')),
            ],
        ),
    ]
