# Generated by Django 5.1.7 on 2025-06-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganado_vacuno',
            name='precio_por_kilo',
            field=models.FloatField(verbose_name='Precio por kilogramo'),
        ),
    ]
